#!/usr/bin/env node
// PreToolUse hook for Edit / Write / MultiEdit. Blocks writes to paths that are
// generated, vendored, or owned by a tool — where a hand edit is silently lost on
// the next build and costs someone an afternoon to work out why.
//
// Exit 0 = allow. Exit 2 = block. Any internal error exits 0.

const PROTECTED = [
  {
    re: /(^|[\/\\])node_modules[\/\\]/,
    why: "installed by npm; edits vanish on the next install",
  },
  { re: /(^|[\/\\])\.expo[\/\\]/, why: "generated by the Expo CLI" },
  {
    re: /(^|[\/\\])(android|ios)[\/\\]/,
    why: "generated by prebuild; change app.json or a config plugin instead",
  },
  { re: /(^|[\/\\])(dist|build|coverage)[\/\\]/, why: "build output" },
  {
    re: /package-lock\.json$/,
    why: "regenerate it with 'npm install' rather than editing it by hand",
  },
  { re: /expo-env\.d\.ts$/, why: "generated by Expo" },
  { re: /(^|[\/\\])\.git[\/\\]/, why: "git internals" },
];

function main(raw) {
  let path = "";
  try {
    const input = JSON.parse(raw);
    path = input?.tool_input?.file_path ?? input?.tool_input?.path ?? "";
  } catch {
    return 0;
  }
  if (!path) return 0;

  for (const rule of PROTECTED) {
    if (rule.re.test(path)) {
      process.stderr.write(
        `Blocked write to a protected path — ${rule.why}.\n  ${path}\n` +
          `If this really is the right place to change, say so and a person can do it deliberately.\n`,
      );
      return 2;
    }
  }
  return 0;
}

let input = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (c) => (input += c));
process.stdin.on("end", () => {
  let code = 0;
  try {
    code = main(input);
  } catch {
    code = 0; // fail open
  }
  process.exit(code);
});
